### PR TITLE
Fixing incorrect code in readme

### PR DESCRIPTION
**Pull request by RusseII**
"store" does not exist. Changed it to use the Store object that the user created earlier.

### CODE REVIEW

**Comment by RusseII** [comment]
did you have a chance to look at this?

**Comment by RusseII** [comment]
@Magicjarvis

**Comment by Magicjarvis** [comment]
Thanks!

**Comment by RusseII** [comment]
@Magicjarvis can you please merge this with the master branch? (got accepted but not merged) Thanks!

**Pull request merged**
